-- -------------------------------------------------------------------------------------------------
-- Database Name: mosip_keymgr
-- Table Name   : 
-- Purpose      : All the FKs are created separately, not part of create table scripts to ease the deployment process
--           
-- Create By    : Sadanandegowda DM
-- Created Date : Sep-2019
-- 
-- Modified Date        Modified By         Comments / Remarks
-- ------------------------------------------------------------------------------------------
-- 
-- ------------------------------------------------------------------------------------------

