\c mosip_keymgr 

GRANT CONNECT
   ON DATABASE mosip_keymgr
   TO keymgruser;

GRANT USAGE
   ON SCHEMA keymgr
   TO keymgruser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
   ON ALL TABLES IN SCHEMA keymgr
   TO keymgruser;

ALTER DEFAULT PRIVILEGES IN SCHEMA keymgr 
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO keymgruser;

