language: java
jdk: openjdk8
install: true
cache:
  directories:
  - $HOME/.m2
script: mvn install -DskipTests=false -Dgpg.skip=true -Dmaven.javadoc.skip=true -DargLine="-Dlogging.level.root=ERROR" -B -V
