//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.constant;

import io.mosip.kernel.biometrics.entities.RegistryIDType;

import java.io.Serializable;

public class QualityType implements Serializable {

	protected RegistryIDType algorithm;
	protected Long score;
	protected String qualityCalculationFailed;

	/**
	 * Gets the value of the algorithm property.
	 * 
	 * @return possible object is {@link RegistryIDType }
	 * 
	 */
	public RegistryIDType getAlgorithm() {
		return algorithm;
	}

	/**
	 * Sets the value of the algorithm property.
	 * 
	 * @param value allowed object is {@link RegistryIDType }
	 * 
	 */
	public void setAlgorithm(RegistryIDType value) {
		this.algorithm = value;
	}

	/**
	 * Gets the value of the score property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getScore() {
		return score;
	}

	/**
	 * Sets the value of the score property.
	 * 
	 * @param value allowed object is {@link Long }
	 * 
	 */
	public void setScore(Long value) {
		this.score = value;
	}

	/**
	 * Gets the value of the qualityCalculationFailed property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getQualityCalculationFailed() {
		return qualityCalculationFailed;
	}

	/**
	 * Sets the value of the qualityCalculationFailed property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setQualityCalculationFailed(String value) {
		this.qualityCalculationFailed = value;
	}

}
