//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.constant;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import io.mosip.kernel.biometrics.entities.RegistryIDType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualityType", propOrder = { "algorithm", "score", "qualityCalculationFailed" })
@Data
@NoArgsConstructor
@AllArgsConstructor
public class QualityType implements Serializable {

	@XmlElement(name = "Algorithm", required = true)
	protected RegistryIDType algorithm;
	@XmlElement(name = "Score")
	@XmlSchemaType(name = "unsignedInt")
	protected Long score;
	@XmlElement(name = "QualityCalculationFailed")
	protected String qualityCalculationFailed;

}
