\c mosip_audit 

GRANT CONNECT
   ON DATABASE mosip_audit
   TO audituser;

GRANT USAGE
   ON SCHEMA audit
   TO audituser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
   ON ALL TABLES IN SCHEMA audit
   TO audituser;

ALTER DEFAULT PRIVILEGES IN SCHEMA audit 
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO audituser;

