\c :mosipdbname

GRANT CONNECT
   ON DATABASE :mosipdbname
   TO :dbunameuser;

GRANT USAGE
   ON SCHEMA :dbuname
   TO :dbunameuser;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
      ON ALL TABLES IN SCHEMA :dbuname
          TO :dbunameuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA :dbuname
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO :dbunameuser;
