//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.entities;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import io.mosip.kernel.biometrics.constant.BiometricType;
import io.mosip.kernel.biometrics.constant.ProcessedLevelType;
import io.mosip.kernel.biometrics.constant.PurposeType;
import io.mosip.kernel.biometrics.constant.QualityType;

public class BDBInfoType {

	
	protected byte[] challengeResponse;
	
	protected String index;
	
	protected RegistryIDType format;
	
	protected Boolean encryption;
	
	protected LocalDateTime creationDate;
	
	protected LocalDateTime notValidBefore;
	
	protected LocalDateTime notValidAfter;
	
	protected List<BiometricType> type;
	
	protected List<String> subtype;
	
	protected ProcessedLevelType level;
	
	protected RegistryIDType product;
	
	protected RegistryIDType captureDevice;

	protected RegistryIDType featureExtractionAlgorithm;
	
	protected RegistryIDType comparisonAlgorithm;
	
	protected RegistryIDType compressionAlgorithm;

	protected PurposeType purpose;
	
	protected QualityType quality;

	/**
	 * Gets the value of the challengeResponse property.
	 * 
	 * @return possible object is byte[]
	 */
	public byte[] getChallengeResponse() {
		return challengeResponse;
	}

	/**
	 * Sets the value of the challengeResponse property.
	 * 
	 * @param value allowed object is byte[]
	 */
	public void setChallengeResponse(byte[] value) {
		this.challengeResponse = value;
	}

	/**
	 * Gets the value of the index property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIndex() {
		return index;
	}

	/**
	 * Sets the value of the index property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setIndex(String value) {
		this.index = value;
	}

	/**
	 * Gets the value of the format property.
	 * 
	 * @return possible object is {@link RegistryIDType }
	 * 
	 */
	public RegistryIDType getFormat() {
		return format;
	}

	/**
	 * Sets the value of the format property.
	 * 
	 * @param value allowed object is {@link RegistryIDType }
	 * 
	 */
	public void setFormat(RegistryIDType value) {
		this.format = value;
	}

	/**
	 * Gets the value of the encryption property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isEncryption() {
		return encryption;
	}

	/**
	 * Sets the value of the encryption property.
	 * 
	 * @param value allowed object is {@link Boolean }
	 * 
	 */
	public void setEncryption(Boolean value) {
		this.encryption = value;
	}

	/**
	 * Gets the value of the creationDate property.
	 * 
	 * @return possible object is {@link LocalDateTime }
	 * 
	 */
	public LocalDateTime getCreationDate() {
		return creationDate;
	}

	/**
	 * Sets the value of the creationDate property.
	 * 
	 * @param value allowed object is {@link LocalDateTime }
	 * 
	 */
	public void setCreationDate(LocalDateTime value) {
		this.creationDate = value;
	}

	/**
	 * Gets the value of the notValidBefore property.
	 * 
	 * @return possible object is {@link LocalDateTime }
	 * 
	 */
	public LocalDateTime getNotValidBefore() {
		return notValidBefore;
	}

	/**
	 * Sets the value of the notValidBefore property.
	 * 
	 * @param value allowed object is {@link LocalDateTime }
	 * 
	 */
	public void setNotValidBefore(LocalDateTime value) {
		this.notValidBefore = value;
	}

	/**
	 * Gets the value of the notValidAfter property.
	 * 
	 * @return possible object is {@link LocalDateTime }
	 * 
	 */
	public LocalDateTime getNotValidAfter() {
		return notValidAfter;
	}

	/**
	 * Sets the value of the notValidAfter property.
	 * 
	 * @param value allowed object is {@link LocalDateTime }
	 * 
	 */
	public void setNotValidAfter(LocalDateTime value) {
		this.notValidAfter = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the type property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getType().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link SingleTypeType }
	 * 
	 * 
	 */
	public List<BiometricType> getType() {
		if (type == null) {
			type = new ArrayList<BiometricType>();
		}
		return this.type;
	}

	/**
	 * Gets the value of the subtype property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the subtype property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubtype().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getSubtype() {
		if (subtype == null) {
			subtype = new ArrayList<String>();
		}
		return this.subtype;
	}

	/**
	 * Gets the value of the level property.
	 * 
	 * @return possible object is {@link ProcessedLevelType }
	 * 
	 */
	public ProcessedLevelType getLevel() {
		return level;
	}

	/**
	 * Sets the value of the level property.
	 * 
	 * @param value allowed object is {@link ProcessedLevelType }
	 * 
	 */
	public void setLevel(ProcessedLevelType value) {
		this.level = value;
	}

	/**
	 * Gets the value of the product property.
	 * 
	 * @return possible object is {@link RegistryIDType }
	 * 
	 */
	public RegistryIDType getProduct() {
		return product;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(List<BiometricType> type) {
		this.type = type;
	}

	/**
	 * @param subtype the subtype to set
	 */
	public void setSubtype(List<String> subtype) {
		this.subtype = subtype;
	}

	/**
	 * Sets the value of the product property.
	 * 
	 * @param value allowed object is {@link RegistryIDType }
	 * 
	 */
	public void setProduct(RegistryIDType value) {
		this.product = value;
	}

	/**
	 * Gets the value of the captureDevice property.
	 * 
	 * @return possible object is {@link RegistryIDType }
	 * 
	 */
	public RegistryIDType getCaptureDevice() {
		return captureDevice;
	}

	/**
	 * Sets the value of the captureDevice property.
	 * 
	 * @param value allowed object is {@link RegistryIDType }
	 * 
	 */
	public void setCaptureDevice(RegistryIDType value) {
		this.captureDevice = value;
	}

	/**
	 * Gets the value of the featureExtractionAlgorithm property.
	 * 
	 * @return possible object is {@link RegistryIDType }
	 * 
	 */
	public RegistryIDType getFeatureExtractionAlgorithm() {
		return featureExtractionAlgorithm;
	}

	/**
	 * Sets the value of the featureExtractionAlgorithm property.
	 * 
	 * @param value allowed object is {@link RegistryIDType }
	 * 
	 */
	public void setFeatureExtractionAlgorithm(RegistryIDType value) {
		this.featureExtractionAlgorithm = value;
	}

	/**
	 * Gets the value of the comparisonAlgorithm property.
	 * 
	 * @return possible object is {@link RegistryIDType }
	 * 
	 */
	public RegistryIDType getComparisonAlgorithm() {
		return comparisonAlgorithm;
	}

	/**
	 * Sets the value of the comparisonAlgorithm property.
	 * 
	 * @param value allowed object is {@link RegistryIDType }
	 * 
	 */
	public void setComparisonAlgorithm(RegistryIDType value) {
		this.comparisonAlgorithm = value;
	}

	/**
	 * Gets the value of the compressionAlgorithm property.
	 * 
	 * @return possible object is {@link RegistryIDType }
	 * 
	 */
	public RegistryIDType getCompressionAlgorithm() {
		return compressionAlgorithm;
	}

	/**
	 * Sets the value of the compressionAlgorithm property.
	 * 
	 * @param value allowed object is {@link RegistryIDType }
	 * 
	 */
	public void setCompressionAlgorithm(RegistryIDType value) {
		this.compressionAlgorithm = value;
	}

	/**
	 * Gets the value of the purpose property.
	 * 
	 * @return possible object is {@link PurposeType }
	 * 
	 */
	public PurposeType getPurpose() {
		return purpose;
	}

	/**
	 * Sets the value of the purpose property.
	 * 
	 * @param value allowed object is {@link PurposeType }
	 * 
	 */
	public void setPurpose(PurposeType value) {
		this.purpose = value;
	}

	/**
	 * Gets the value of the quality property.
	 * 
	 * @return possible object is {@link QualityType }
	 * 
	 */
	public QualityType getQuality() {
		return quality;
	}

	/**
	 * Sets the value of the quality property.
	 * 
	 * @param value allowed object is {@link QualityType }
	 * 
	 */
	public void setQuality(QualityType value) {
		this.quality = value;
	}

}
