//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.entities;

import java.time.LocalDateTime;

public class BIRInfoType {

	
	protected String creator;
	
	protected String index;
	
	protected byte[] payload;
	
	protected boolean integrity;
	
	protected LocalDateTime creationDate;

	protected LocalDateTime notValidBefore;
	
	protected LocalDateTime notValidAfter;

	/**
	 * Gets the value of the creator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * Sets the value of the creator property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCreator(String value) {
		this.creator = value;
	}

	/**
	 * Gets the value of the index property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIndex() {
		return index;
	}

	/**
	 * Sets the value of the index property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setIndex(String value) {
		this.index = value;
	}

	/**
	 * Gets the value of the payload property.
	 * 
	 * @return possible object is byte[]
	 */
	public byte[] getPayload() {
		return payload;
	}

	/**
	 * Sets the value of the payload property.
	 * 
	 * @param value allowed object is byte[]
	 */
	public void setPayload(byte[] value) {
		this.payload = value;
	}

	/**
	 * Gets the value of the integrity property.
	 * 
	 */
	public boolean isIntegrity() {
		return integrity;
	}

	/**
	 * Sets the value of the integrity property.
	 * 
	 */
	public void setIntegrity(boolean value) {
		this.integrity = value;
	}

	/**
	 * Gets the value of the creationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public LocalDateTime getCreationDate() {
		return creationDate;
	}

	/**
	 * Sets the value of the creationDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCreationDate(LocalDateTime value) {
		this.creationDate = value;
	}

	/**
	 * Gets the value of the notValidBefore property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public LocalDateTime getNotValidBefore() {
		return notValidBefore;
	}

	/**
	 * Sets the value of the notValidBefore property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setNotValidBefore(LocalDateTime value) {
		this.notValidBefore = value;
	}

	/**
	 * Gets the value of the notValidAfter property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public LocalDateTime getNotValidAfter() {
		return notValidAfter;
	}

	/**
	 * Sets the value of the notValidAfter property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setNotValidAfter(LocalDateTime value) {
		this.notValidAfter = value;
	}

}
