//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.entities;


public class SBInfoType {

	protected RegistryIDType format;

	/**
	 * Gets the value of the format property.
	 * 
	 * @return possible object is {@link RegistryIDType }
	 * 
	 */
	public RegistryIDType getFormat() {
		return format;
	}

	/**
	 * Sets the value of the format property.
	 * 
	 * @param value allowed object is {@link RegistryIDType }
	 * 
	 */
	public void setFormat(RegistryIDType value) {
		this.format = value;
	}

}
