//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.13 at 03:22:53 PM IST 
//

package io.mosip.kernel.biometrics.entities;


public class VersionType {

	
	protected long major;
	
	protected long minor;

	/**
	 * Gets the value of the major property.
	 * 
	 */
	public long getMajor() {
		return major;
	}

	/**
	 * Sets the value of the major property.
	 * 
	 */
	public void setMajor(long value) {
		this.major = value;
	}

	/**
	 * Gets the value of the minor property.
	 * 
	 */
	public long getMinor() {
		return minor;
	}

	/**
	 * Sets the value of the minor property.
	 * 
	 */
	public void setMinor(long value) {
		this.minor = value;
	}

}
