apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-server.fullname" . }}
  labels:
    {{- include "config-server.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.spring_profiles.enabled }}
  {{- range $index, $repo := .Values.spring_profiles.spring_compositeRepos }}
  {{- if $repo.token }}
  SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_{{ $index }}_PASSWORD: {{ $repo.token | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
