name: Add Branch Protection

on:
  push:
    branches:
      - develop

jobs:
  add-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add branch protection rule 
        run: |
          TOKEN=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
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer  $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Rakshithb1/commons/branches/develop/protection/required_status_checks/contexts \
            -d '{"contexts":["kernel-idgenerator-service / build-dockers","kernel-notification-service / build-dockers"]}'
