name: Add Branch Protection 

on:
  push:
    branches:
      - develop

jobs:
  add-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          

      - name: Add branch protection rule 
        run: |
           curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer 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" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Rakshithb1/commons/branches/develop/protection/required_status_checks/contexts  \
              -d '{"contexts":["build-commons / maven-build","kernel-notification-service / build-dockers"]}'
