name: Add Branch Protection

on:
  push:
    branches:
      - develop

jobs:
  add-branch-protection:
    runs-on: ubuntu-latest
    env: 
     G_TOKEN: ${{ secrets.SSTOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: uuuu branch protection rule 
        run: |
         curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $G_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Rakshithb1/commons/branches/develop/protection/required_status_checks

