name: Branch Protection

on:
  push:
    branches:
      - develop

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    env: 
     G_TOKEN: ${{ secrets.SSTOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      


      - name: Add branch protection rule
        run: |
          for line in $(tail -n +2 .github/workflows/check.csv); do
            REPO_NAME=$(echo $line | cut -d ',' -f 1)
            BRANCH_NAME=$(echo $line | cut -d ',' -f 2)
            CHECK=$(echo $line | cut -d ',' -f 3)

            set -x  # Enable debugging

            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $G_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$REPO_NAME/branches/$BRANCH_NAME/protection/required_status_checks/contexts" \
              -d '{"contexts":["'$CHECK'"]}'
          done
