name: Branch Protection

on:
  workflow_dispatch:
    inputs:
      api_method:
        description: 'Provide API method (ADD, GET, DELETE)'
        required: true
        default: ''
        type: string

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    env: 
     G_TOKEN: ${{ secrets.SSTOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Get branch protection rule
        run: |
         tail -n +2 .github/workflows/check.csv | while IFS=, read -r REPO_NAME BRANCH_NAME CHECKS; do
           curl -L \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $G_TOKEN" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$REPO_NAME/branches/$BRANCH_NAME/protection/required_status_checks/contexts
         done     

      - name: Add branch protection rule
        run: |
          tail -n +2 .github/workflows/check.csv | while IFS=, read -r REPO_NAME BRANCH_NAME CHECKS; do
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $G_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$REPO_NAME/branches/$BRANCH_NAME/protection/required_status_checks/contexts" \
              -d "{\"contexts\":[\"$CHECKS\"]}"
          done
