name: Branch Protection

on:
  push:
    branches:
      - develop

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    env: 
     G_TOKEN: ${{ secrets.SSTOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read values from CSV
        id: read-values
        run: |
          cd .github/workflows
          CSV_CONTENT=$(tail -n +2 check.csv)
          echo "REPO_NAMES=$(echo "$CSV_CONTENT" | cut -d ',' -f 1 | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
          echo "BRANCH_NAMES=$(echo "$CSV_CONTENT" | cut -d ',' -f 2 | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
          echo "CHECKS=$(echo "$CSV_CONTENT" | cut -d ',' -f 3 | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV



      - name: Add branch protection rule
        run: |
          REPO_NAMES=($REPO_NAMES)
          BRANCH_NAMES=($BRANCH_NAMES)
          CHECKS=($CHECKS)

          for i in $(seq 0 $((${#REPO_NAMES[@]} - 1))); do
            REPO_NAME=${REPO_NAMES[$i]}
            BRANCH_NAME=${BRANCH_NAMES[$i]}
            CHECK=${CHECKS[$i]}

            # Create a branch protection rule
            curl -X PUT \
              -H "Authorization: Bearer $G_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$REPO_NAME/branches/$BRANCH_NAME/protection" \
              -d "{
                \"required_status_checks\": {
                  \"contexts\": [\"$CHECK\"]
                }
              }"
          done


